### ISSUE TITLE
i cannot upload the code

### ISSUE THREAD

**Issue by LaurensMarkwat** [grafmar/Arduino-Reflow-Oven#5]
Dear Grafmar,

I am verry interrested in your project and would like to make it myself but when I want to upload the code to the arduino it does not work so could you help me?

kind regards,

Laurens Markwat

**Comment by grafmar** [comment]
Hi Laurens,
What kind of display do you use?
in ReflowOven.h you can specify (line 9 and 10) one of two types:
- ST7781, which uses the SWTFT library included in the source
- SPFD5408, which uses the TftSpfd5408 library. This you have to install from Arduino-IDE->Sketch->Include Library->Manage Libraries

Best is if you can test your Display with a Library-Example and extend the ReflowOven.h file with the used pins and Touch parameters if needed.

kind regards,
  Marco Graf

**Comment by grafmar** [comment]
Hi,

Okay, that was the hint needed ;-)
in "Adafruit GFX Library V1.5.0" there was a variable textsize. In the deriving classes SWTFT or TftSpfd5408 respectively this variable is initialized. Adafruit changed this to textsize_x and textsize_y.
So, get this working. Install Adafruit GFX Library V1.5.0 (this can be selected in the Library manager: search GFX, and in Adafruit GFX Library search in "Select version". Or you can update your driver-library by replacing in "TftSpfd5408.cpp" file the line `textsize  = 1;` in
```
textsize_x  = 1;
textsize_y  = 1;
```

kind regards,
  Marco Graf

**Comment by LaurensMarkwat** [comment]
Thank you very much for your help. I have tried your suggestion and it is working. If I have further questions during the build I will contact you again. Thank you very much
